# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zlC9swKkG6ki1xjc4iapiwJAXLfVTDXS
"""

import sympy as sym

def custom_latex_printer(exp,**options):
    from google.colab.output._publish import javascript
    url = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.3/latest.js?config=default"
    javascript(url=url)
    return sym.printing.latex(exp,**options)
sym.init_printing(use_latex="mathjax",latex_printer=custom_latex_printer)
# 讓他print出漂亮算式的方法

a, b = sym.symbols('a, b')

expr = (a + b) ** 2 
expr

sym.init_printing()

expr.expand()

expr2 = (a+b)*(a-b)
sym.init_printing()
expr2.expand()
