# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ddqPKw4nMWnQNx39OeR_UUl6bi3ONAIp
"""

import numpy as np

A = np.matrix([[1,2,3,4],
               [4,3,2,1],
               [3,4,1,2],
               [2,1,4,3]])

A ** 2 - 24

B = np.matrix([[2,4,1,3],
               [4,2,3,1],
               [1,3,2,4],
               [3,1,4,2]])

A * B

B * A

A2 = np.matrix([[1,-1],
               [2,1]])

A2 ** 2 - 2 * A2 + 3

B2 = np.matrix([[1,0],
                [0,1]])
x = np.linalg.solve(A2,B2)
x