# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zlC9swKkG6ki1xjc4iapiwJAXLfVTDXS
"""

import sympy as sym

a, b = sym.symbols('a, b')

expr = (a + b) ** 2 
expr

sym.init_printing()

expr.expand()

expr2 = (a+b)*(a-b)
sym.init_printing()
expr2.expand()